/**
 * JIRA Integration Service
 * Handles creating and managing JIRA stories from test cases
 */

export interface JiraConfig {
  url: string;
  username: string;
  apiToken: string;
  projectKey?: string;
}

export interface TestCase {
  description: string;
  compliance: string[];
}

export interface RequirementTestCase {
  requirement: string;
  testCases: TestCase[];
}

export interface JiraStoryResponse {
  success: boolean;
  key?: string;
  error?: string;
}

/**
 * Creates a JIRA story with test cases
 */
export async function createJiraStory(
  config: JiraConfig,
  requirement: RequirementTestCase,
  fileName: string,
  requirementIndex: number
): Promise<JiraStoryResponse> {
  try {
    // Create Basic Auth header
    const authString = `${config.username}:${config.apiToken}`;
    const encodedAuth = btoa(authString);

    // Format the description with test cases
    const description = formatJiraDescription(requirement);

    // Get project key from config or try to extract from URL
    const projectKey = config.projectKey || extractProjectKey(config.url);

    if (!projectKey) {
      return {
        success: false,
        error: 'Project key is required. Please configure it in the Integrations page.',
      };
    }

    // Create the story payload
    const payload = {
      fields: {
        project: {
          key: projectKey,
        },
        summary: `[${fileName}] Requirement #${requirementIndex + 1}: ${requirement.requirement.substring(0, 100)}${requirement.requirement.length > 100 ? '...' : ''}`,
        description: description,
        issuetype: {
          name: 'Story',
        },
        labels: ['healthtestai', 'automated-test-cases'],
      },
    };

    // Make API call to create issue
    const response = await fetch(`${config.url}/rest/api/3/issue`, {
      method: 'POST',
      headers: {
        'Authorization': `Basic ${encodedAuth}`,
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      console.error('JIRA API Error:', errorData);
      return {
        success: false,
        error: errorData.errorMessages?.[0] || `HTTP ${response.status}: ${response.statusText}`,
      };
    }

    const data = await response.json();
    return {
      success: true,
      key: data.key,
    };
  } catch (error) {
    console.error('Error creating JIRA story:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error occurred',
    };
  }
}

/**
 * Formats the test cases into JIRA description format
 */
function formatJiraDescription(requirement: RequirementTestCase): string {
  let description = `h2. Requirement\n\n${requirement.requirement}\n\n`;
  description += `h2. Test Cases (${requirement.testCases.length})\n\n`;

  requirement.testCases.forEach((tc, index) => {
    description += `h3. Test Case ${index + 1}\n\n`;
    description += `${tc.description}\n\n`;

    if (tc.compliance && tc.compliance.length > 0) {
      description += `*Compliance Standards:* ${tc.compliance.join(', ')}\n\n`;
    }

    description += '---\n\n';
  });

  description += '\n_Generated by HealthTestAI_';

  return description;
}

/**
 * Attempts to extract project key from JIRA URL or project name
 */
function extractProjectKey(url: string): string | null {
  try {
    // Try to extract from URL path like /browse/PROJ-123
    const match = url.match(/\/browse\/([A-Z]+)-/);
    if (match) {
      return match[1];
    }

    // Default to null, will need to be configured
    return null;
  } catch {
    return null;
  }
}

/**
 * Validates JIRA configuration
 */
export function validateJiraConfig(config: JiraConfig): boolean {
  return !!(
    config.url &&
    config.username &&
    config.apiToken &&
    config.url.includes('atlassian.net') &&
    (config.projectKey || extractProjectKey(config.url))
  );
}

/**
 * Exports all test cases to JIRA as separate stories
 */
export async function exportAllToJira(
  config: JiraConfig,
  requirements: RequirementTestCase[],
  fileName: string,
  onProgress?: (current: number, total: number, key?: string) => void
): Promise<{ success: number; failed: number; errors: string[] }> {
  const results = {
    success: 0,
    failed: 0,
    errors: [] as string[],
  };

  for (let i = 0; i < requirements.length; i++) {
    const requirement = requirements[i];
    const result = await createJiraStory(config, requirement, fileName, i);

    if (result.success) {
      results.success++;
      onProgress?.(i + 1, requirements.length, result.key);
    } else {
      results.failed++;
      results.errors.push(`Requirement #${i + 1}: ${result.error}`);
      onProgress?.(i + 1, requirements.length);
    }

    // Add a small delay to avoid rate limiting
    if (i < requirements.length - 1) {
      await new Promise(resolve => setTimeout(resolve, 500));
    }
  }

  return results;
}
