/**
 * JIRA Integration Service
 * Handles creating and managing JIRA stories from test cases
 */

export interface JiraConfig {
  url: string;
  username: string;
  apiToken: string;
  projectKey?: string;
}

export interface TestCase {
  description: string;
  compliance: string[];
}

export interface RequirementTestCase {
  requirement: string;
  testCases: TestCase[];
}

export interface JiraStoryResponse {
  success: boolean;
  key?: string;
  error?: string;
}

/**
 * Creates a JIRA task with test cases
 */
export async function createJiraStory(
  config: JiraConfig,
  requirement: RequirementTestCase,
  fileName: string,
  requirementIndex: number
): Promise<JiraStoryResponse> {
  try {
    // Format the description with test cases
    const description = formatJiraDescription(requirement);

    // Get project key from config or try to extract from URL
    const projectKey = config.projectKey || extractProjectKey(config.url);

    if (!projectKey) {
      return {
        success: false,
        error: 'Project key is required. Please configure it in the Integrations page.',
      };
    }

    // Extract requirement ID (e.g., REQ-INT-001) from the requirement text
    const reqIdMatch = requirement.requirement.match(/REQ-[A-Z]+-\d+/);
    const summary = reqIdMatch ? reqIdMatch[0] : `Requirement #${requirementIndex + 1}`;

    // Create the task payload (using Task instead of Story for HEAL project)
    const payload = {
      fields: {
        project: {
          key: projectKey,
        },
        summary: summary,
        description: description,
        issuetype: {
          name: 'Task',  // Changed from 'Story' to 'Task' for HEAL project
        },
        labels: ['healthtestai', 'automated-test-cases'],
      },
    };

    // Make API call to our server-side proxy
    const response = await fetch('/api/jira/create-issue', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        url: config.url,
        username: config.username,
        apiToken: config.apiToken,
        payload: payload,
      }),
    });

    const data = await response.json();

    if (!response.ok || !data.success) {
      console.error('JIRA API Error:', JSON.stringify(data, null, 2));
      console.error('Error details:', data.details);
      console.error('Sent payload:', data.sentPayload);
      return {
        success: false,
        error: data.error || `HTTP ${response.status}: ${response.statusText}`,
      };
    }

    return {
      success: true,
      key: data.key,
    };
  } catch (error) {
    console.error('Error creating JIRA story:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error occurred',
    };
  }
}

/**
 * Formats the test cases into JIRA ADF (Atlassian Document Format)
 */
function formatJiraDescription(requirement: RequirementTestCase): any {
  const content: any[] = [
    {
      type: 'heading',
      attrs: { level: 2 },
      content: [{ type: 'text', text: 'Requirement' }],
    },
    {
      type: 'paragraph',
      content: [{ type: 'text', text: requirement.requirement }],
    },
    {
      type: 'heading',
      attrs: { level: 2 },
      content: [{ type: 'text', text: `Test Cases (${requirement.testCases.length})` }],
    },
  ];

  requirement.testCases.forEach((tc, index) => {
    // Test case heading
    content.push({
      type: 'heading',
      attrs: { level: 3 },
      content: [{ type: 'text', text: `Test Case ${index + 1}` }],
    });

    // Test case description
    content.push({
      type: 'paragraph',
      content: [{ type: 'text', text: tc.description }],
    });

    // Compliance standards
    if (tc.compliance && tc.compliance.length > 0) {
      content.push({
        type: 'paragraph',
        content: [
          { type: 'text', text: 'Compliance Standards: ', marks: [{ type: 'strong' }] },
          { type: 'text', text: tc.compliance.join(', ') },
        ],
      });
    }

    // Separator
    content.push({
      type: 'rule',
    });
  });

  // Footer
  content.push({
    type: 'paragraph',
    content: [{ type: 'text', text: 'Generated by HealthTestAI', marks: [{ type: 'em' }] }],
  });

  return {
    version: 1,
    type: 'doc',
    content: content,
  };
}

/**
 * Attempts to extract project key from JIRA URL or project name
 */
function extractProjectKey(url: string): string | null {
  try {
    // Try to extract from URL path like /browse/PROJ-123
    const match = url.match(/\/browse\/([A-Z]+)-/);
    if (match) {
      return match[1];
    }

    // Default to null, will need to be configured
    return null;
  } catch {
    return null;
  }
}

/**
 * Validates JIRA configuration
 */
export function validateJiraConfig(config: JiraConfig): boolean {
  return !!(
    config.url &&
    config.username &&
    config.apiToken &&
    config.url.includes('atlassian.net') &&
    (config.projectKey || extractProjectKey(config.url))
  );
}

/**
 * Exports all test cases to JIRA as separate stories
 */
export async function exportAllToJira(
  config: JiraConfig,
  requirements: RequirementTestCase[],
  fileName: string,
  onProgress?: (current: number, total: number, key?: string) => void
): Promise<{ success: number; failed: number; errors: string[] }> {
  const results = {
    success: 0,
    failed: 0,
    errors: [] as string[],
  };

  for (let i = 0; i < requirements.length; i++) {
    const requirement = requirements[i];
    const result = await createJiraStory(config, requirement, fileName, i);

    if (result.success) {
      results.success++;
      onProgress?.(i + 1, requirements.length, result.key);
    } else {
      results.failed++;
      results.errors.push(`Requirement #${i + 1}: ${result.error}`);
      onProgress?.(i + 1, requirements.length);
    }

    // Add a small delay to avoid rate limiting
    if (i < requirements.length - 1) {
      await new Promise(resolve => setTimeout(resolve, 500));
    }
  }

  return results;
}
